name: Workflow - Release
on:
  push:
    branches:
      - 'release/*'
jobs:
  check-php-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring
      - name: Check installed php modules
        run: php -m
